# typed: true
# frozen_string_literal: true

# Homebrew formula for kommand0 — auto-generated by
# scripts/render-homebrew-formula.sh on each release. Edits here are overwritten.
class Kommand0 < Formula
  desc "Keyboard-first local orchestrator for parallel Claude Code sessions"
  homepage "https://github.com/cstuncsik/kommand0"
  # version is intentionally omitted: Homebrew derives it from the URL, and an
  # explicit stanza would be flagged redundant by brew audit.
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cstuncsik/kommand0/releases/download/v0.27.0/kommand0-v0.27.0-macos-universal.tar.gz"
      sha256 "1f3d4b9dba5ef48e4c9e1e94f29663b9efd0b3efe2d5577d3b62ccc71946a234"
    end
    on_intel do
      url "https://github.com/cstuncsik/kommand0/releases/download/v0.27.0/kommand0-v0.27.0-macos-universal.tar.gz"
      sha256 "1f3d4b9dba5ef48e4c9e1e94f29663b9efd0b3efe2d5577d3b62ccc71946a234"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cstuncsik/kommand0/releases/download/v0.27.0/kommand0-v0.27.0-linux-x86_64.tar.gz"
      sha256 "412b7849c0998e3c89849ad12d4b5c090d1175e54386493f39a5e5cf1a6e94df"
    end
  end

  def install
    bin.install "kommand0", "kmd"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kommand0 --version")
    assert_match version.to_s, shell_output("#{bin}/kmd --version")
  end
end
