# typed: true
# frozen_string_literal: true

# Homebrew formula for kommand0 — auto-generated by
# scripts/render-homebrew-formula.sh on each release. Edits here are overwritten.
class Kommand0 < Formula
  desc "Keyboard-first local orchestrator for parallel Claude Code sessions"
  homepage "https://github.com/cstuncsik/kommand0"
  # version is intentionally omitted: Homebrew derives it from the URL, and an
  # explicit stanza would be flagged redundant by brew audit.
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cstuncsik/kommand0/releases/download/v0.18.2/kommand0-v0.18.2-macos-universal.tar.gz"
      sha256 "a3ad53c573b9375a6d050ae3123a9e2513f60942e1de61f0b9417591763ae032"
    end
    on_intel do
      url "https://github.com/cstuncsik/kommand0/releases/download/v0.18.2/kommand0-v0.18.2-macos-universal.tar.gz"
      sha256 "a3ad53c573b9375a6d050ae3123a9e2513f60942e1de61f0b9417591763ae032"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cstuncsik/kommand0/releases/download/v0.18.2/kommand0-v0.18.2-linux-x86_64.tar.gz"
      sha256 "d1b96e95a2c9583486b4493c1a7dba16aefedf97ad37efadf390586ccdda53f5"
    end
  end

  def install
    bin.install "kommand0", "kmd"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kommand0 --version")
    assert_match version.to_s, shell_output("#{bin}/kmd --version")
  end
end
