# typed: true
# frozen_string_literal: true

# Homebrew formula for kommand0 — auto-generated by
# scripts/render-homebrew-formula.sh on each release. Edits here are overwritten.
class Kommand0 < Formula
  desc "Keyboard-first local orchestrator for parallel Claude Code sessions"
  homepage "https://github.com/cstuncsik/kommand0"
  # version is intentionally omitted: Homebrew derives it from the URL, and an
  # explicit stanza would be flagged redundant by brew audit.
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/cstuncsik/kommand0/releases/download/v0.25.3/kommand0-v0.25.3-macos-universal.tar.gz"
      sha256 "c101f025f95eb7e4bb778394ff9297bb5eb6b8eaffa0e566f3f0d6666785957c"
    end
    on_intel do
      url "https://github.com/cstuncsik/kommand0/releases/download/v0.25.3/kommand0-v0.25.3-macos-universal.tar.gz"
      sha256 "c101f025f95eb7e4bb778394ff9297bb5eb6b8eaffa0e566f3f0d6666785957c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cstuncsik/kommand0/releases/download/v0.25.3/kommand0-v0.25.3-linux-x86_64.tar.gz"
      sha256 "d1540db01c3d4f2341e9145712ad494ee9fa3e314daeabca9603c43a858c5a5a"
    end
  end

  def install
    bin.install "kommand0", "kmd"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kommand0 --version")
    assert_match version.to_s, shell_output("#{bin}/kmd --version")
  end
end
